const routers = {
	home: '/',
	signin: '/signin',
	singup: '/signup',
	forgorpwd: '/forgotPassword',
	verifyOtp: '/verifyOTP',
	about: '/discover/about',
	parties: '/discover/parties',
	gallery: '/discover/gallery',
	video: '/discover/video',
	sponsers: '/meet/sponsers',
	exhibitor: '/meet/exhibitor',
	mediaPartners: '/meet/media-partners',
	attendess: '/meet/attendees',
	agenda: '/discuss/agenda',
	speakers: '/discuss/speakers',
	floorplan: '/engage/floorplan',
	faq: '/engage/faq',
	venue: '/engage/venue',
	transportation: '/engage/transportation',
	accommodation: '/engage/accommodation',
	contact: '/engage/contact-us',
};
export default routers;
